export const DESTINATIONS = [
    { label: 'Crematorio: Burzaco' },
    { label: 'Cementerio: Camposanto' },
    { label: 'Crematorio: Cementerio Libertad' },
    { label: 'Cementerio: Chacarita' },
    { label: 'Cementerio: Colonial' },
    { label: 'Cementerio: Flores' },
    { label: 'Cementerio: Jardin de Paz Pilar' },
    { label: 'Cementerio: Lar de Paz' },
    { label: 'Cementerio: Las Praderas' },
    { label: 'Cementerio: Libertad' },
    { label: 'Crematorio: Lomas de Zamora' },
    { label: 'Crematorio: Los Ceibos' },
    { label: 'Cementerio: Los Ceibos' },
    { label: 'Crematorio: Monte Paraiso' },
    { label: 'Cementerio: Moron' },
    { label: 'Crematorio: Moron' },
    { label: 'Cementerio: Olivos' },
    { label: 'Cementerio: Pablo Podesta', },
    { label: 'Cementerio: Paraguay' },
    { label: 'Cementerio: Parque Hurlingham', },
    { label: 'Cementerio: Parque Iraola' },
    { label: 'Cementerio: San Justo' },
    { label: 'Cementerio: San Martin' },
    { label: 'Crematorio: San Martin' },
    { label: 'Cementerio: Villegas' },
  ];